//
//  DetailViewController.swift
//  omdb-example
//
//  Created by Juanita Vyatri on 03/12/18.
//  Copyright (c) 2018 Vyatri. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Kingfisher

protocol DetailDisplayLogic: class
{
    
}

class DetailViewController: UIViewController, DetailDisplayLogic
{
    var interactor: DetailBusinessLogic?
    var router: (NSObjectProtocol & DetailRoutingLogic & DetailDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = DetailInteractor()
        let router = DetailRouter()
        viewController.interactor = interactor
        viewController.router = router
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        doDisplay()
    }
    
    // MARK: Do something
    
    var filmDetail: FilmDetail!
    @IBOutlet weak var imageView: UIImageView!
    @IBOutlet weak var titleLabel: UILabel!
    @IBOutlet weak var ratingLabel: UILabel!
    @IBOutlet weak var writerLabel: UILabel!
    @IBOutlet weak var directorLabel: UILabel!
    @IBOutlet weak var genreLabel: UILabel!
    @IBOutlet weak var plotLabel: UILabel!
    @IBOutlet weak var actorLabel: UILabel!
    
    func doDisplay()
    {
        filmDetail = (router?.dataStore?.filmDetail)!
        if (filmDetail.Poster != "N/A") {
            imageView.kf.setImage(with: URL(string: filmDetail.Poster))
            titleLabel.text = filmDetail.Title
            ratingLabel.text = "⭐️ \(filmDetail.imdbRating) (\(filmDetail.imdbVotes) votes)"
            writerLabel.text = "Written by \(filmDetail.Writer)"
            directorLabel.text = "Directed by \(filmDetail.Director)"
            genreLabel.text = "Genre: \(filmDetail.Genre)"
            plotLabel.text = filmDetail.Plot
            actorLabel.text = "Actors: \(filmDetail.Actors)"
        }
    }
    
}
