//
//  MasterRouter.swift
//  omdb-example
//
//  Created by Juanita Vyatri on 01/12/18.
//  Copyright (c) 2018 Vyatri. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MasterRoutingLogic
{
    func routeToDetail(_ filmDetail: FilmDetail)
}

protocol MasterDataPassing
{
    var dataStore: MasterDataStore? { get }
}

class MasterRouter: NSObject, MasterRoutingLogic, MasterDataPassing
{
    weak var viewController: MasterViewController?
    var dataStore: MasterDataStore?
    
    // MARK: Routing
    
    func routeToDetail(_ filmDetail: FilmDetail)
    {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "detailPage") as! DetailViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToDetail(filmData: filmDetail, destination: &destinationDS)
        navigateToDetail(source: viewController!, destination: destinationVC)
    }
    
    // MARK: Navigation
    
    func navigateToDetail(source: MasterViewController, destination: DetailViewController)
    {
        source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    func passDataToDetail(filmData: FilmDetail, destination: inout DetailDataStore)
    {
        destination.filmDetail = filmData
    }
}
