//
//  OMDBWorker.swift
//  omdb-example
//
//  Created by Juanita Vyatri on 01/12/18.
//  Copyright (c) 2018 Vyatri. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class OMDBWorker
{
    
    
    func doSearch(_ keyword: String, page: Int = 1) -> [Film]
    {
        
    }
    
    func getResultsFromDB(_ keyword: String) -> [Film]
    {
        
    }
    
    func saveResults(_ results: [Film], onpage: Int) -> Bool
    {
        
    }
    
    func getLastSearchBreakpoinnt(_ keyword: String) -> History
    {
        
    }
    
    func saveLastBreakpoint(_ history: History) -> Bool
    {
        
    }
}
