//
//  OMDBWorker.swift
//  omdb-example
//
//  Created by Juanita Vyatri on 01/12/18.
//  Copyright (c) 2018 Vyatri. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire

class OMDBWorker
{
    
    
    func doSearch(_ keyword: String, page: Int = 1, completion: @escaping (FilmList?) -> Void)
    {
        let parameters: Parameters = [
            "i": "tt3896198", "apikey": "58aba22c", "r": "json",
            "s": keyword.lowercased(),
            "page": page
        ]
        Alamofire.request("https://www.omdbapi.com/", parameters: parameters).validate().responseData { response in
            switch response.result {
            case .success:
                if let data = response.result.value {
                    do {
                        let decoder = JSONDecoder()
                        let gitData = try decoder.decode(FilmList.self, from: data)
                        completion(gitData)
                    } catch let err {
                        print("Err", err)
                        completion(nil)
                    }
                } else {
                    completion(nil)
                }
            case .failure( _):
                completion(nil)
            }
        }
    }
    
    func getResultsFromDB(_ keyword: String) -> [Film]
    {
        return []
    }
    
    func saveResults(_ results: [Film], onpage: Int) -> Bool
    {
        return true
    }
    
    func getLastSearchBreakpoinnt(_ keyword: String) -> History?
    {
        return nil
    }
    
    func saveLastBreakpoint(_ history: History) -> Bool
    {
        return true
    }
}
