//
//  DetailInteractor.swift
//  omdb-example
//
//  Created by Juanita Vyatri on 03/12/18.
//  Copyright (c) 2018 Vyatri. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailBusinessLogic
{
}

protocol DetailDataStore
{
    var filmDetail: FilmDetail! { get set}
}

class DetailInteractor: DetailBusinessLogic, DetailDataStore
{
    var filmDetail: FilmDetail!
    
}
