
//
//  MasterInteractor.swift
//  omdb-example
//
//  Created by Juanita Vyatri on 01/12/18.
//  Copyright (c) 2018 Vyatri. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MasterBusinessLogic
{
  func doSomething(request: Master.Something.Request)
}

protocol MasterDataStore
{
  //var name: String { get set }
}

class MasterInteractor: MasterBusinessLogic, MasterDataStore
{
  var presenter: MasterPresentationLogic?
  var worker: MasterWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Master.Something.Request)
  {
    worker = MasterWorker()
    worker?.doSomeWork()
    
    let response = Master.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
